CREATE TABLE IF NOT EXISTS `reglogindb`.`registrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `reg_email` VARCHAR(45) NULL DEFAULT NULL,
  `reg_password` VARCHAR(255) NULL DEFAULT NULL,
  `reg_passwordconf` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8